# Generated by Django 5.0 on 2024-01-06 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_created=True, null=True)),
                ('product_name', models.CharField(max_length=150)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_created=True, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=13)),
                ('address', models.CharField(max_length=100)),
                ('index', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shtamplangan_detallar.productmodel')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'confirmed'), (2, 'processing'), (3, 'fineshed')], default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shtamplangan_detallar.ordermodel')),
            ],
        ),
        migrations.CreateModel(
            name='GaleryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='media/photo')),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p', to='shtamplangan_detallar.productmodel')),
            ],
        ),
    ]
