# Generated by Django 5.0 on 2023-12-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todomodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='important',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='completed',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
