# Generated by Django 5.0 on 2023-12-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todomodel_important_alter_todomodel_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='description',
            field=models.TextField(default=' '),
        ),
    ]
